### ISSUE TITLE
[UNKNOWN_THEME_VALUE] and [UNKNOWN_DIRECTIVE] on Nextjs 12 in extended theme values

### ISSUE THREAD

**Issue by rodrigojmr** [tw-in-js/use-twind-with#24]
Hello,

I'm aware the package was updated to support Nextjs 12, but when I upgrade Next, I get these errors. 

![image](https://user-images.githubusercontent.com/11283573/141371251-707692a8-e77d-4076-9c3b-94171b24bff4.png)
I have a theme extended in `twind.config.ts` (some part of the code deleted for legibility) and then used on `theme.extend`.

![image](https://user-images.githubusercontent.com/11283573/141372290-7bd9f9f7-ac43-4107-80b7-3d83aa241624.png)

The only difference between this happening or not is being on Next 11.1.2 or 120.3.
It causes styles to get messed up, adding styles to the wrong places, and some not being used at all. Interestingly, it seems similar to this issue but I'm unsure. https://github.com/tw-in-js/twind/issues/47

If I navigate away from a page then return, then the styles are correct.

https://user-images.githubusercontent.com/11283573/141371963-07103b16-e269-4a36-b1a2-5dd12709d648.mp4

**Comment by Omar-Aziz** [comment]
Same thing here,
![CleanShot 2021-12-16 at 02 18 38](https://user-images.githubusercontent.com/23618431/146333970-7c64409a-094e-433b-87f1-9074ca66c7ea.png)

```typescript
import withTwindDocuemnt from '@twind/next/shim/document'
import Document, { Head, Html, Main, NextScript } from 'next/document'
import { setup } from 'twind'
import twindConfig from 'twind.config'

setup({
  theme: twindConfig.theme,
  darkMode: twindConfig.darkMode,
  mode: 'silent',
  preflight: true,
})

class RootDocument extends Document {
  static async getInitialProps(ctx: any) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }
  render() {
    return (
      <Html className="dark">
        <Head />
        <Main />
        <NextScript />
      </Html>
    )
  }
}
export default withTwindDocuemnt(twindConfig, RootDocument)
```

**Comment by sastan** [comment]
Hey. Sorry for the late reply.

@rodrigojmr  I need to take a closer at that. is it possible for you to create a codesandbox for reproduction?

@Omar-Aziz Seams similar. But the `color/opacity` stuff will not work with twind v0.16. I hope to release a v0.17 with support for these and most changes from tailwind v3.

**Comment by Omar-Aziz** [comment]
thanks for the clarification @sastan. Does JIT work in twind and if yes then does it need any config?

**Comment by sastan** [comment]
> thanks for the clarification @sastan. Does JIT work in twind and if yes then does it need any config?

twind only generates the styles for the classes that are used. We didn't call it JIT. As a side note I do not think of tailwind JIT as a just-in-time generator. It generates all classes it finds in the code base during a build step. twind generates only those classes that are used.

**Comment by rodrigojmr** [comment]
Just want to inform I'm still trying to replicate in a smaller version of the client's site. I started with copying and removing code to make a slimmer, shareable version of the site, then Omar's error tipped me off to an error in my config as well. After fixing that, it worked fine in the slimmed down site but still not in the client app. Now it's hard to trace back at which deleted code may be causing this issue, but still experimenting.

**Comment by rodrigojmr** [comment]
Well this is embarrassing!

It all comes down to calling `tw` outside className and outside components, and not `apply`, in attempt to reuse classes. Due to #12 and other similar logs to this, I had turned twind mode to silent, but only with NextJS 12 do these logs seem to happen regardless of the mode, and also cause the app to malfunction. Had no such problems in 11, so I was blissfully, ignorantly unaware of the misuse of `tw`.

**Comment by sastan** [comment]
Ah I see. Closing this for now. Feel free to re-open if you have any more trouble.
