### ISSUE TITLE
@twind/wmr: style tag does not populate with styles with prerender

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/use-twind-with#6]
Apologies if this is intentional, though I'm not quite sure why it would be.

It appears the style tag that gets generated on prerender is not populated with the styles of the application. This can be seen using the example WMR app: https://github.com/tw-in-js/example-wmr. Simply build the application, remove the JS imports from the built HTML/disable JS and you'll see none of the styling is there to be applied.

**Comment by sastan** [comment]
Thanks for the report. This was not intentional. It had something to do with async hooks scoping (00aa9ca). 

Could you please try @twind/wmr@1.0.5.

**Comment by rschristian** [comment]
Odd issue, but looks good to me! Thanks!
