### ISSUE TITLE
@twind/next doesn't load custom twind.config.js

### ISSUE THREAD

**Issue by danestves** [tw-in-js/use-twind-with#7]
Hi! Thank you for the library, i don't know if i'm missing something or what but if i add a custom config for `twind` the styles doesn't work anymore https://codesandbox.io/s/twind-nextjs-forked-l5r91?file=/twind.config.js

**Comment by sastan** [comment]
TL;DR replace `@twind/next/app` with `@twind/next/shim/app` and `@twind/next/document` with `@twind/next/shim/document`

You are using the `className` attribute for styling and therefore need the shim modules: https://github.com/tw-in-js/use-twind-with/tree/main/examples/next-with-shim

See the [this (forked) sandbox](https://codesandbox.io/s/twind-nextjs-forked-jtgjs?file=/pages/_document.js)

In twind you can either do:

```js
import { tw } from 'twind'

<main className={tw`h-screen bg-purple-400 flex items-center justify-center`}>
  <h1 className={tw`font-bold text(center 5xl white sm:gray-800 md:pink-700)`}>
    This is Twind!
  </h1>
</main>
```

Or use the shim:

```jsx
<main className="h-screen bg-purple-400 flex items-center justify-center">
  <h1 className="font-bold text(center 5xl white sm:gray-800 md:pink-700)">This is Twind!</h1>
</main>
```

**Comment by danestves** [comment]
OMG, i think im lost today! Thank you for the clarification, and if i want to use it mixed i can't right? On with shim or without?

**Comment by sastan** [comment]
Nope. You can use both! No problem.

**Comment by danestves** [comment]
Thank you!!!
