### ISSUE TITLE
@twind/preact: tw and css options cannot be enabled without breakage

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/use-twind-with#9]
## Reproduction
[The CodeSandbox linked in the ReadMe reproduces the error](https://codesandbox.io/s/thirsty-banzai-smrpi?fontsize=14&hidenavigation=1&theme=dark). You'll be met by `cannot use 'in' operator to search for "tw" in "This is Twind!"`

## Explanation
Errors are thrown when searching for the [`tw`](https://github.com/tw-in-js/use-twind-with/blob/9d2934eddc401ea1beef775d0b1ef80d303f2ea3/packages/preact/index.ts#L55) and [`css`](https://github.com/tw-in-js/use-twind-with/blob/9d2934eddc401ea1beef775d0b1ef80d303f2ea3/packages/preact/index.ts#L62) props on an element with text content, assuming those options are enabled. The text content will have `props` of whatever the content is, i.e., `"This is Twind!"`. Can't use the `in` operator to search on a string.

## Solution?
I'm not sure why that method is used to begin with (`"tw" in props`), but solution could be as simple as switching that to `props.tw` or just checking to ensure `props` is an object first. I don't have the background knowledge here, so you'll likely know better.

**Comment by danielweck** [comment]
missing sanity check for vnode.type:
https://github.com/tw-in-js/use-twind-with/blob/9d2934eddc401ea1beef775d0b1ef80d303f2ea3/packages/preact/index.ts#L51

**Comment by sastan** [comment]
fixed in v1.0.5

**Comment by rschristian** [comment]
Thanks!
